#############################################################################
# Makefile for building: bin/kno
# Generated by qmake (2.01a) (Qt 4.3.3) on: Sat Mar 29 16:43:42 2008
# Project:  kno.pro
# Template: app
# Command: /usr/lib/qt-4.3.3/bin/qmake -unix -o Makefile kno.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/lib/qt-4.3.3/mkspecs/linux-g++ -I. -I/usr/lib/qt-4.3.3/include/QtCore -I/usr/lib/qt-4.3.3/include/QtCore -I/usr/lib/qt-4.3.3/include/QtNetwork -I/usr/lib/qt-4.3.3/include/QtNetwork -I/usr/lib/qt-4.3.3/include/QtGui -I/usr/lib/qt-4.3.3/include/QtGui -I/usr/lib/qt-4.3.3/include -Ibuild -Ibuild
LINK          = g++
LFLAGS        = -Wl,-rpath,/usr/lib/qt-4.3.3/lib
LIBS          = $(SUBLIBS)  -L/usr/lib/qt-4.3.3/lib -lQtGui -L/usr/lib/qt-4.3.3/lib -L/usr/X11R6/lib -lpng -lSM -lICE -pthread -pthread -lXi -lXrender -lXrandr -lXfixes -lXcursor -lXinerama -lfreetype -lfontconfig -lXext -lX11 -lQtNetwork -pthread -pthread -lQtCore -lz -lm -pthread -lgthread-2.0 -lrt -lglib-2.0 -ldl -lpthread
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/lib/qt-4.3.3/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -sf
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = build/

####### Files

SOURCES       = src/knoFirstImpl.cpp \
		src/main.cpp \
		src/aboutknodialogimpl.cpp \
		src/knoGameimpl.cpp \
		src/polewidget.cpp build/moc_knoFirstImpl.cpp \
		build/moc_aboutknodialogimpl.cpp \
		build/moc_knoGameimpl.cpp \
		build/moc_polewidget.cpp \
		qrc_lbl.cpp
OBJECTS       = build/knoFirstImpl.o \
		build/main.o \
		build/aboutknodialogimpl.o \
		build/knoGameimpl.o \
		build/polewidget.o \
		build/moc_knoFirstImpl.o \
		build/moc_aboutknodialogimpl.o \
		build/moc_knoGameimpl.o \
		build/moc_polewidget.o \
		build/qrc_lbl.o
DIST          = /usr/lib/qt-4.3.3/mkspecs/common/g++.conf \
		/usr/lib/qt-4.3.3/mkspecs/common/unix.conf \
		/usr/lib/qt-4.3.3/mkspecs/common/linux.conf \
		/usr/lib/qt-4.3.3/mkspecs/qconfig.pri \
		/usr/lib/qt-4.3.3/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/release.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/qt.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/moc.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/resources.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/uic.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/lex.prf \
		kno.pro
QMAKE_TARGET  = kno
DESTDIR       = bin/
TARGET        = bin/kno

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET): build/ui_knoFirst.h build/ui_aboutKNO.h build/ui_knoGame.h $(OBJECTS)  
	@$(CHK_DIR_EXISTS) bin/ || $(MKDIR) bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kno.pro  /usr/lib/qt-4.3.3/mkspecs/linux-g++/qmake.conf /usr/lib/qt-4.3.3/mkspecs/common/g++.conf \
		/usr/lib/qt-4.3.3/mkspecs/common/unix.conf \
		/usr/lib/qt-4.3.3/mkspecs/common/linux.conf \
		/usr/lib/qt-4.3.3/mkspecs/qconfig.pri \
		/usr/lib/qt-4.3.3/mkspecs/features/qt_functions.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/qt_config.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/default_pre.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/release.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/default_post.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/warn_on.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/qt.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/unix/thread.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/moc.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/resources.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/uic.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/yacc.prf \
		/usr/lib/qt-4.3.3/mkspecs/features/lex.prf \
		/usr/lib/qt-4.3.3/lib/libQtGui.prl \
		/usr/lib/qt-4.3.3/lib/libQtCore.prl \
		/usr/lib/qt-4.3.3/lib/libQtNetwork.prl
	$(QMAKE) -unix -o Makefile kno.pro
/usr/lib/qt-4.3.3/mkspecs/common/g++.conf:
/usr/lib/qt-4.3.3/mkspecs/common/unix.conf:
/usr/lib/qt-4.3.3/mkspecs/common/linux.conf:
/usr/lib/qt-4.3.3/mkspecs/qconfig.pri:
/usr/lib/qt-4.3.3/mkspecs/features/qt_functions.prf:
/usr/lib/qt-4.3.3/mkspecs/features/qt_config.prf:
/usr/lib/qt-4.3.3/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt-4.3.3/mkspecs/features/default_pre.prf:
/usr/lib/qt-4.3.3/mkspecs/features/release.prf:
/usr/lib/qt-4.3.3/mkspecs/features/default_post.prf:
/usr/lib/qt-4.3.3/mkspecs/features/warn_on.prf:
/usr/lib/qt-4.3.3/mkspecs/features/qt.prf:
/usr/lib/qt-4.3.3/mkspecs/features/unix/thread.prf:
/usr/lib/qt-4.3.3/mkspecs/features/moc.prf:
/usr/lib/qt-4.3.3/mkspecs/features/resources.prf:
/usr/lib/qt-4.3.3/mkspecs/features/uic.prf:
/usr/lib/qt-4.3.3/mkspecs/features/yacc.prf:
/usr/lib/qt-4.3.3/mkspecs/features/lex.prf:
/usr/lib/qt-4.3.3/lib/libQtGui.prl:
/usr/lib/qt-4.3.3/lib/libQtCore.prl:
/usr/lib/qt-4.3.3/lib/libQtNetwork.prl:
qmake:  FORCE
	@$(QMAKE) -unix -o Makefile kno.pro

dist: 
	@$(CHK_DIR_EXISTS) build/kno1.0.0 || $(MKDIR) build/kno1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) build/kno1.0.0/ && $(COPY_FILE) --parents src/knoFirstImpl.h src/aboutknodialogimpl.h src/knoGameimpl.h src/polewidget.h build/kno1.0.0/ && $(COPY_FILE) --parents ui/lbl.qrc build/kno1.0.0/ && $(COPY_FILE) --parents src/knoFirstImpl.cpp src/main.cpp src/aboutknodialogimpl.cpp src/knoGameimpl.cpp src/polewidget.cpp build/kno1.0.0/ && $(COPY_FILE) --parents ui/knoFirst.ui ui/aboutKNO.ui ui/knoGame.ui build/kno1.0.0/ && $(COPY_FILE) --parents russian.ts build/kno1.0.0/ && (cd `dirname build/kno1.0.0` && $(TAR) kno1.0.0.tar kno1.0.0 && $(COMPRESS) kno1.0.0.tar) && $(MOVE) `dirname build/kno1.0.0`/kno1.0.0.tar.gz . && $(DEL_FILE) -r build/kno1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: build/moc_knoFirstImpl.cpp build/moc_aboutknodialogimpl.cpp build/moc_knoGameimpl.cpp build/moc_polewidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) build/moc_knoFirstImpl.cpp build/moc_aboutknodialogimpl.cpp build/moc_knoGameimpl.cpp build/moc_polewidget.cpp
build/moc_knoFirstImpl.cpp: build/ui_knoFirst.h \
		src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h \
		src/knoGameimpl.h \
		build/ui_knoGame.h \
		build/polewidget.h \
		src/knoFirstImpl.h
	/usr/lib/qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) src/knoFirstImpl.h -o build/moc_knoFirstImpl.cpp

build/moc_aboutknodialogimpl.cpp: build/ui_aboutKNO.h \
		src/aboutknodialogimpl.h
	/usr/lib/qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) src/aboutknodialogimpl.h -o build/moc_aboutknodialogimpl.cpp

build/moc_knoGameimpl.cpp: build/ui_knoGame.h \
		build/polewidget.h \
		src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h \
		src/knoGameimpl.h
	/usr/lib/qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) src/knoGameimpl.h -o build/moc_knoGameimpl.cpp

build/moc_polewidget.cpp: src/polewidget.h
	/usr/lib/qt-4.3.3/bin/moc $(DEFINES) $(INCPATH) src/polewidget.h -o build/moc_polewidget.cpp

compiler_rcc_make_all: qrc_lbl.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_lbl.cpp
qrc_lbl.cpp: ui/lbl.qrc \
		russian.qm \
		ui/lbl.jpg
	/usr/lib/qt-4.3.3/bin/rcc -name lbl ui/lbl.qrc -o qrc_lbl.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: build/ui_knoFirst.h build/ui_aboutKNO.h build/ui_knoGame.h
compiler_uic_clean:
	-$(DEL_FILE) build/ui_knoFirst.h build/ui_aboutKNO.h build/ui_knoGame.h
build/ui_knoFirst.h: ui/knoFirst.ui
	/usr/lib/qt-4.3.3/bin/uic ui/knoFirst.ui -o build/ui_knoFirst.h

build/ui_aboutKNO.h: ui/aboutKNO.ui
	/usr/lib/qt-4.3.3/bin/uic ui/aboutKNO.ui -o build/ui_aboutKNO.h

build/ui_knoGame.h: ui/knoGame.ui
	/usr/lib/qt-4.3.3/bin/uic ui/knoGame.ui -o build/ui_knoGame.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean compiler_uic_clean 

####### Compile

build/knoFirstImpl.o: src/knoFirstImpl.cpp src/knoFirstImpl.h \
		build/ui_knoFirst.h \
		src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h \
		src/knoGameimpl.h \
		build/ui_knoGame.h \
		build/polewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/knoFirstImpl.o src/knoFirstImpl.cpp

build/main.o: src/main.cpp src/knoFirstImpl.h \
		build/ui_knoFirst.h \
		src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h \
		src/knoGameimpl.h \
		build/ui_knoGame.h \
		build/polewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/main.o src/main.cpp

build/aboutknodialogimpl.o: src/aboutknodialogimpl.cpp src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/aboutknodialogimpl.o src/aboutknodialogimpl.cpp

build/knoGameimpl.o: src/knoGameimpl.cpp src/knoGameimpl.h \
		build/ui_knoGame.h \
		build/polewidget.h \
		src/aboutknodialogimpl.h \
		build/ui_aboutKNO.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/knoGameimpl.o src/knoGameimpl.cpp

build/polewidget.o: src/polewidget.cpp build/polewidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/polewidget.o src/polewidget.cpp

build/moc_knoFirstImpl.o: build/moc_knoFirstImpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_knoFirstImpl.o build/moc_knoFirstImpl.cpp

build/moc_aboutknodialogimpl.o: build/moc_aboutknodialogimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_aboutknodialogimpl.o build/moc_aboutknodialogimpl.cpp

build/moc_knoGameimpl.o: build/moc_knoGameimpl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_knoGameimpl.o build/moc_knoGameimpl.cpp

build/moc_polewidget.o: build/moc_polewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/moc_polewidget.o build/moc_polewidget.cpp

build/qrc_lbl.o: qrc_lbl.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o build/qrc_lbl.o qrc_lbl.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

